<?php

namespace Database\Seeders;

use App\Models\Skill;
use Illuminate\Database\Seeder;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds
     *
     * @return void
     */
    public function run()
    {
        $skills = collect([
            ['name' => 'README.md', 'experience' => 100, 'excerpt' => "Over the past 7+ years, 5 of which spent building ticketing software with the great people at <span class='text-hmt-green underline font-bold text-xl'>HoldMyTicket</span>, I've gained a lot of confidence in many technologies, languages, and software. These are the tools that help me effenciently build complex, interactive, responsive, and secure web applications. Some of these I am just now learning, and others I've been hacking with for years."],
            ['name' => 'hire me', 'experience' => 101, 'excerpt' => "Whoa, really? You're in need a some web development work? If so, I'm very excited to out more about this..."],
            ['name' => 'reset();', 'experience' => 102, 'excerpt' => "refreshing!"],
            ['name' => 'CSS', 'experience' => 91, 'excerpt' => "The first time I interacted with CSS was back in the 7th grade. I took a beginner course at my middle school. Considering I was born in the late 80's, and lived out in the middle of nowhere New Mexico, this was a fairly unique opportunity. I remember most of the home work was learning HTML, and writing markup over and over. While bored writing div's p's and a's, I browsed around for some cool menus I've been seeing on the internet. I found a few examples, and spent the rest of the time building my own drop down menu with CSS. Don't think I ever actually finished the home work, and probably passed with a C. But I learned more than anyone in that class, no doubt. Needless to say, I'm pretty comfortable with CSS."],
            ['name' => 'HTML', 'experience' => 98, 'excerpt' => "Well here it is, the sharpest tool in the tool box. Now, this isn't due to an enormous amount of time spent digging into through depths of the W3C's stadards for the standard web markup language, but nearly 20 years spent interacting with this fairly simplistic markup. Perhaps Photoshop has been in the tool bag for the longest, however the depths of Photoshop prove to be humbling."],
            ['name' => 'Javascript', 'experience' => 91, 'excerpt' => "I really enjoy JavaScript. I've spent more effort deep diving JavaScript than any other programming language I know. Fasinated by its effeciency, and versitility, I keep re-watching a video series from Kyle Simpson, end up in a deep vortex on https://developer.mozilla.org/, or just hacking out ideas in Developer tools just with JavaScript. I've touched a handful of frameworks, but usually end up just wanting to write my own vanilla in the current stable ECMAScript standard. At HoldMyTicket, a lot of riot.js.org (specifically up to v3) was used. From building offline first native mobile with RiotJs and Pusher, to public facing SPA's selling millions of tickets a year, JavaScript has been there for me."],
            ['name' => 'PHP', 'experience' => 96, 'excerpt' => "Like many, my first server side language was PHP. Unlike many, I actually like PHP. While working as a product photographer at a Native American Art Gallery, Wright's Indian Art, I started digging around the company's website code. It turned out to be a VERY large PHP application, written by a very talented programmer. Nothing but performance first procedural PHP, and 10's of thousands of lines of it. At HoldMyTicket, a heavily extended CodeIgniter 2 backend was found, and here is really where I made sense of all my OOP studies. If I have deadlines, need to prototype something, need to write a quick script to parse a text file, want to scrape the web, I use PHP."],
            ['name' => 'Linux', 'experience' => 77, 'excerpt' => "All my laptops have Linux on them, my main machine has a dual-boot Linux/Windows, and every web server I have ever managed has been Linux. I love Linux. If I could have Adobe's Create Suite native in Linux I'd never leave. Over the years I've gained a good amount of experience in package management, user management, service management, software management, and scripting. Now Linux is broad. Real broad. So until I'm writing my own Kernels, I'll give myself a 77. For a web developer, I'd say that's pretty good. Oh, yea, I think I'm suppose to tell you I use Arch."],
            ['name' => 'Laravel', 'experience' => 78, 'excerpt' => "Back when I was digging through thousands of lines of procedural PHP, I thought there had to be a better way. Turns out Laravel 5.1 was just out, and everyone on the internet was talking about it. I tried my hand at re-writing an my current job's web app with Laravel. I got pretty far and showed the owner, unfortunately the owner didn't want to overwrite the current system, and my hard work never saw the light of day. I have just recently started working with Laravel again, this time understanding what's under the hood a whole lot better. It turns out everyone on the internet was right to talk about it. I wrote this site in Laravel, and am currently working on two other side projects with it too. I'm giving myself a 78 here, but I'm certain by the end of April 2021, this will be in the 90's."],
            ['name' => 'CodeIgniter', 'experience' => 79, 'excerpt' => "I worked on ticketing software for 5 years on a CodeIgniter 2 backend. It was extended a fair amount, and there was PHP code that lived outside of it. There was never an option to upgrade to a newer version of it. So really, I don't know any modern CodeIgniter, and the CodeIgniter I do know, was all hacked up. But I do know PHP, and that was all I needed to get work done."],
            ['name' => 'Docker', 'experience' => 86, 'excerpt' => "After assisting in Docker-izing a group of load balanced Nginx PHP sites, and experimenting in migrating Vagrant local developments over to Docker and Kubernetes I feel pretty comfortable configuring web applications with Docker. I tend to reach for it less when deploying my personal applications, but with Laravel Sail, better local OS integrations, I feel like I'll be sharpening this tool more and more."],
            ['name' => 'Vagrant', 'experience' => 88, 'excerpt' => "Another skill set of mine to start from Laravel would be Vagrant. I have used Vagrant for my local development for the past 7 years. This is always with Oracle VM VirtualBox, and always feel very comfortable to configure it the way I need. Typically if I am spinning up a quick test box, I'll just use VirtualBox. However, for long term consistent local development this feels at home. Will Docker take me over? :P"],
            ['name' => 'Kubernetes', 'experience' => 84, 'excerpt' => "Man, do I feel cool when I am working with Kubernetes. I've helped move some of the main services at HoldMyTicket over to utilize Kubernetes, and I hope to build something of my own that needs Kubernetes to really establish a stream lined deployment, management, and scaling process. There is a lot more under the tip that I have uncovered, and I hope in the next few years I get to explore. It's a space that I enjoy."],
            ['name' => 'Digital Ocean', 'experience' => 93, 'excerpt' => "All my personal projects, and a few professional ones all live on Digital Ocean. I've put static sites, proxy sites, streaming video sites, real time chat sites. From Ubuntu to Arch, Databases to Kubernetes, Droplets to Spaces, I use it all. I am also familiar with Heroku, and some AWS, but if I'd have the choice, I'd stay with Digital Ocean."],
            ['name' => 'Networking', 'experience' => 76, 'excerpt' => "Somehow at a, ticketing software company, I found myself configuring a Repeater Bridge Wireless Network via modems flashed with DD-WRT firmware connected to multiple access ports providing connectivity to RFID Scanners to track and validate entry at a remove festival in the jungle, Costa Rica. I don't process any Network certificates, but the countless hours troubleshooting network configurations provide enough of a badge for me to put this experience score in the 70s."],
            ['name' => 'Redis', 'experience' => 88, 'excerpt' => "Majority of the web apps I hack on have Redis. What a fantastic technology. I'll admit, those web apps are mostly using Redis as a cache, and what a wonderful cache it is, however I am creating a new web app that uses it more as a database for products, shopping cart, and search functionality. It is a pretty versatile technology, and I keep finding more and more uses for it."],
            ['name' => 'SQL', 'experience' => 84, 'excerpt' => "Well, really for me, this is MySQL. Nearly all SQL interaction for me has been with MySQL. It took me a pretty long time to get really comfortable seeing the big picture relational databases. I'm no master here, and my previous CTO could always shave a few hundred milliseconds (probably even more honestly) off my polished queries. That said, I gained a lot of confidence here, especially in the past couple years."],
            ['name' => 'tailwindcss', 'experience' => 63, 'excerpt' => "Well, this thing you are interacting with right now, is officially the first project of mine to have tailwindcss in production. I have mixed feeling about this thing still. I love the dead simple way to get my bundle tiny. I freaking love tiny bundles. I still find it kind of tedious though. To me it takes bit more work to keep everything DRY. I'm still constantly referencing the docs, and typing the pure css way first. This may stay at the same experience level."],
            ['name' => 'Vim', 'experience' => 75, 'excerpt' => "I'm the guy with his dotfiles version controlled. This is for my Vim, and Tmux setup. I love Vim. Keyboards are home for me. I customize them, collect them, build them, photograph them. I don't want to leave it, and touch my mouse. I'm always customizing my .vimrc, plugins, and keybindings. Learning new shortcuts, and ways to get what I need to do done faster. Now I've seen people on the internet also use Vim, they make me look like a noob. It drives me to master my IDE."],
            ['name' => 'Bash', 'experience' => 74, 'excerpt' => "I've built a few shell scripts for automating server builds, some others for personal computer configurations, and backups. But I also spend majority of my time inside a Bash terminal. I'm not winning any bash one liner script competitions, and am googling syntax all the time, but sometimes I forget how much I interact with the Bourne Again SHell. Thanks, Brian Fox."],
            ['name' => 'Heroku', 'experience' => 63, 'excerpt' => "I've been deploying production apps through Heroku for a while now. Server configuration files, spinning up more instances, integrating a continuous testing suite. No problems here. My go to is still Digital Ocean though."],
            ['name' => 'NodeJS', 'experience' => 43, 'excerpt' => "The idea of only writing Javascript is very appealing to me. I was actually toying with idea of actually writing this site with Node.js. And I mean Node.js, not express, hapi.js, sails, just Node.js. I also thought about picking of GoLang. But ultimately this tiny public facing side doesn't warrant the need for it. I hope a project comes along that will. If not, I may re-write this with some service that may utilize better, and I can increase the meter on this one."],
            ['name' => 'GoLang', 'experience' => 21, 'excerpt' => "I've just recently begun the journey on this language. I want to learn a statically typed, compiled programming language. I feel like it will form me into a better programmer all around, and am excited about the doors it may open. Naturally my first experiments with it have been for web servers, but I want to pull the scope back a bit, and write some 'real' softwares."],
            ['name' => 'Python', 'experience' => 31, 'excerpt' => "I guess I'm more of a PHP guy. Most of my friends use Python day in and out, and I know how much they enjoy it. I have jumped in some scripts and made the changes necessary for the functionality that was required, and didn't struggle much. Thanks to its readability, and friendliness, my experience level for Python is a little higher than it probably should be."],
            ['name' => 'riot.js.org', 'experience' => 85],
            ['name' => 'NGINX', 'experience' => 84],
            ['name' => 'APACHE', 'experience' => 62],
            ['name' => 'Git', 'experience' => 94, 'excerpt' => ""],
            ['name' => 'GitHub', 'experience' => 60, 'excerpt' => "Hey what gives? I have been using this for over 7 years, why is my experience so low here. Github has pull requests, issues, actions, projects, insights, marketplace, stars, follows, ratings, forks, integrations, and like tons more. I pretty much use things thing for a repository interface, and storage. Well anyways, the best way for me to show you my GitHub experience is with my profile page. Shake me up and down to open my GitHub profile in new tab."],
            ['name' => 'Vue', 'experience' => 36],
            ['name' => 'React', 'experience' => 55],
            ['name' => 'Bootstrap', 'experience' => 41],
            ['name' => 'JQuery', 'experience' => 76],
            ['name' => 'npm', 'experience' => 86],
            ['name' => 'webpack', 'experience' => 55],
            ['name' => 'Cloudinary', 'experience' => 73],
            ['name' => 'Photoshop', 'experience' => 94],
            ['name' => 'Illustrator', 'experience' => 89],
            ['name' => 'Figma', 'experience' => 35],
        ]);

        foreach ($skills as $skill) {
            Skill::create($skill);
        }
    }
}
