<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A practical five-pass landing page critique method for finding unclear claims, weak hierarchy, generic design, misplaced proof, and costly edits.">
    <link rel="canonical" href="{{ route('character-pass.guide') }}">
    <meta property="og:type" content="article">
    <meta property="og:title" content="How to Critique a Landing Page | Revert Creations">
    <meta property="og:description" content="Five tests that separate a page with character from a polished template—and turn critique into an ordered edit plan.">
    <meta property="og:url" content="{{ route('character-pass.guide') }}">
    <title>How to Critique a Landing Page: Five Useful Passes | Revert Creations</title>
    <script type="application/ld+json">{!! json_encode([
        '@context' => 'https://schema.org',
        '@graph' => [
            ['@type' => 'Article', 'headline' => 'How to Critique a Landing Page: Five Useful Passes', 'description' => 'A practical critique method for landing-page claims, hierarchy, proof, character, and edit priority.', 'author' => ['@type' => 'Organization', 'name' => 'Revert Creations'], 'publisher' => ['@type' => 'Organization', 'name' => 'Revert Creations'], 'mainEntityOfPage' => route('character-pass.guide'), 'datePublished' => '2026-08-05', 'dateModified' => '2026-08-05'],
            ['@type' => 'FAQPage', 'mainEntity' => [
                ['@type' => 'Question', 'name' => 'What should a landing page critique include?', 'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'A useful critique identifies the page claim, reading order, evidence placement, distinctive visual rules, and the highest-leverage edits in priority order.']],
                ['@type' => 'Question', 'name' => 'Is a landing page critique the same as a conversion audit?', 'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'No. A visual critique can identify clarity, hierarchy, trust, and character problems, but it cannot prove conversion impact without behavioral data and a valid experiment.']],
            ]],
        ],
    ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) !!}</script>
    <style>
        :root{--ink:#171713;--paper:#f3efe5;--acid:#d8ff4f;--red:#db482f;--muted:#6b695f}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Arial,Helvetica,sans-serif}a{color:inherit}.bar,header,section,footer{border-bottom:1px solid var(--ink)}.bar,header,main,footer{padding-left:clamp(20px,7vw,110px);padding-right:clamp(20px,7vw,110px)}.bar{padding-top:10px;padding-bottom:10px;display:flex;justify-content:space-between;font:700 11px/1.3 monospace;letter-spacing:.11em;text-transform:uppercase}header{padding-top:25px;padding-bottom:25px;display:flex;justify-content:space-between}.brand{font:700 14px/1 monospace;text-decoration:none}.hero{padding:90px 0 70px;display:grid;grid-template-columns:1.45fr .55fr;gap:7vw}.eyebrow{font:700 11px/1.5 monospace;letter-spacing:.13em;text-transform:uppercase}h1,h2{font-family:Georgia,serif;font-weight:500;letter-spacing:-.055em}h1{font-size:clamp(58px,8vw,116px);line-height:.88;margin:22px 0 32px;max-width:1020px}h2{font-size:clamp(39px,5vw,67px);line-height:.95;margin:0}.intro{font:22px/1.42 Georgia,serif;max-width:760px}.aside{background:var(--red);padding:28px;align-self:end;font:700 14px/1.45 monospace}.method{padding:72px 0}.pass{display:grid;grid-template-columns:100px .8fr 1.2fr;gap:34px;padding:34px 0;border-top:1px solid var(--ink)}.number{font:500 47px/1 Georgia,serif}.pass h3{margin:0;font:500 30px/1.05 Georgia,serif;letter-spacing:-.03em}.pass p,.pass li{font:17px/1.52 Georgia,serif}.pass p{margin:0 0 14px}.pass ul{margin:0;padding-left:20px}.exercise{background:var(--ink);color:var(--paper);padding:65px clamp(20px,7vw,110px);margin-left:calc(-1 * clamp(20px,7vw,110px));margin-right:calc(-1 * clamp(20px,7vw,110px));display:grid;grid-template-columns:.8fr 1.2fr;gap:8vw}.exercise ol{margin:0;padding-left:22px;font:18px/1.65 Georgia,serif}.caution{padding:62px 0;display:grid;grid-template-columns:.8fr 1.2fr;gap:8vw}.caution p{font:18px/1.55 Georgia,serif;margin:0}.cta{background:var(--acid);padding:55px clamp(20px,7vw,110px);margin-left:calc(-1 * clamp(20px,7vw,110px));margin-right:calc(-1 * clamp(20px,7vw,110px));display:flex;justify-content:space-between;align-items:end;gap:40px}.cta p{font:18px/1.45 Georgia,serif;max-width:670px}.button{display:inline-block;background:var(--ink);color:var(--paper);padding:18px 22px;text-decoration:none;font:700 12px/1 monospace;text-transform:uppercase;white-space:nowrap}.button:hover{background:var(--red)}footer{padding-top:25px;padding-bottom:25px;display:flex;justify-content:space-between;font:11px/1.4 monospace}@media(max-width:780px){.hero,.exercise,.caution{grid-template-columns:1fr}.pass{grid-template-columns:60px 1fr}.pass>div:last-child{grid-column:2}.cta{align-items:flex-start;flex-direction:column}.bar span:last-child{display:none}}
    </style>
</head>
<body>
<div class="bar"><span>Revert Creations · field guide 01</span><span>Useful critique before decoration</span></div>
<header><a class="brand" href="{{ route('home') }}">REVERT CREATIONS</a><a href="{{ route('services') }}">Active services →</a></header>
<main>
    <section class="hero"><div><div class="eyebrow">A practical method, not a scorecard</div><h1>The five-pass landing page critique.</h1><p class="intro">Most critiques become inventories of preferences: make the button brighter, shorten the headline, add testimonials. A useful critique does something harder. It identifies what the page is trying to make true, shows where the visual system obscures that truth, and orders the repairs.</p></div><aside class="aside">Use this on one public page. Take notes before changing anything. If every observation becomes an edit, you are decorating—not diagnosing.</aside></section>
    <section class="method">
        <article class="pass"><div class="number">01</div><h3>The five-second claim test</h3><div><p>Look at the first screen for five seconds, then hide it. Write one sentence: “This is for ___ who need ___, and it gives them ___.”</p><ul><li>If you cannot fill all three blanks, the claim is incomplete.</li><li>If your sentence uses words absent from the page, the design is asking the viewer to invent the offer.</li><li>If three elements compete to complete the sentence, hierarchy—not copy length—is probably the first problem.</li></ul></div></article>
        <article class="pass"><div class="number">02</div><h3>The reading-order trace</h3><div><p>Without reading closely, mark the first five things your eye visits. That path is the page’s actual argument. Compare it with the argument the business intended.</p><p>A logo → navigation → decorative image → tiny claim → generic button path is not neutral. It spends attention before explaining value. Repair sequence before polishing components.</p></div></article>
        <article class="pass"><div class="number">03</div><h3>The proof-distance test</h3><div><p>Circle every meaningful claim, then locate the nearest evidence: example, constraint, demonstration, customer result, price, or concrete process detail. Measure distance in scrolls rather than pixels.</p><p>Proof that arrives after skepticism has hardened is weaker proof. Move the most relevant evidence beside the claim it supports; do not create a ceremonial “social proof section” merely because templates have one.</p></div></article>
        <article class="pass"><div class="number">04</div><h3>The character subtraction</h3><div><p>Imagine replacing the logo and brand name with a competitor’s. Which visual decisions would become false? If the answer is “none,” the page may be polished but interchangeable.</p><p>Do not solve this by adding novelty everywhere. Find one repeatable rule—scale contrast, image treatment, typographic tension, material reference, or rhythm—that belongs to the offer. Character is a constraint applied consistently.</p></div></article>
        <article class="pass"><div class="number">05</div><h3>The edit-economics pass</h3><div><p>Sort observations into preserve, consolidate, move, remove, and remake. Then rank them by leverage divided by cost.</p><ul><li>First: unclear offer and broken reading order.</li><li>Second: distant proof and conflicting calls to action.</li><li>Third: a distinctive visual rule.</li><li>Last: isolated cosmetic improvements that leave the argument unchanged.</li></ul></div></article>
    </section>
    <section class="exercise"><h2>A 20-minute critique you can run today.</h2><ol><li>Capture the page at desktop and mobile widths.</li><li>Write the five-second claim from memory.</li><li>Number the first five visual stops.</li><li>Draw a line from each major claim to its nearest proof.</li><li>Name one visual rule a competitor could not honestly inherit.</li><li>Choose only three edits: one clarity repair, one proof repair, and one character move.</li></ol></section>
    <section class="caution"><h2>Know what this cannot prove.</h2><p>A critique can reveal ambiguity, hierarchy, trust, repetition, and generic visual language. It cannot prove that an edit will increase conversion. That requires suitable traffic, behavioral evidence, and a valid comparison. Treat confident conversion promises made from a screenshot alone as sales language—not measurement. See a <a href="{{ route('character-pass.sample') }}"><strong>complete, explicitly limited sample critique</strong></a>.</p></section>
    <section class="cta"><div><div class="eyebrow">An archived method</div><h2>Use the framework freely.</h2><p>This guide remains public, but the associated paid landing-page audit has been retired. Revert Creations currently sells only the clearly bounded Shopify services listed on the services page.</p></div><a class="button" href="{{ route('services') }}">See active services →</a></section>
</main>
<footer><span>© {{ date('Y') }} Revert Creations</span><span>support@revertcreations.com</span></footer>
</body>
</html>
