<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="A free pre-holiday storefront check for Shopify merchants: find broken purchase paths, mobile friction, and layout failures before Black Friday traffic arrives."><link rel="canonical" href="{{ route('storefront-audit.guide') }}"><title>The Pre-Holiday Storefront Check | Revert Creations</title>
<style>:root{--ink:#191914;--paper:#f1eee4;--signal:#ef5b35;--acid:#d8ed55}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Arial,sans-serif}a{color:inherit}.bar,header,footer{padding:14px clamp(20px,7vw,108px);border-bottom:1px solid;display:flex;justify-content:space-between;gap:20px;font:700 11px/1.4 monospace;letter-spacing:.1em;text-transform:uppercase}header{padding-top:24px;padding-bottom:24px}.brand{text-decoration:none}main{padding:0 clamp(20px,7vw,108px);max-width:1100px}h1,h2,h3{font-family:Georgia,serif;font-weight:500;letter-spacing:-.05em}h1{font-size:clamp(44px,6.5vw,84px);line-height:.9;margin:60px 0 24px}h2{font-size:clamp(30px,4vw,48px);line-height:1;margin:55px 0 16px}.lead{font:20px/1.55 Georgia,serif;max-width:760px}p,li{font:17px/1.6 Georgia,serif;max-width:760px}.check{border:1px solid;background:#fffdf7;padding:22px 26px;margin:20px 0;box-shadow:8px 8px 0 var(--signal)}.check h3{margin:0 0 10px;font-size:24px}.check p{margin:8px 0}.check .how{font:13px/1.6 monospace}.cta{background:var(--acid);padding:44px clamp(20px,7vw,108px);margin:60px calc(-1 * clamp(20px,7vw,108px)) 0;display:flex;justify-content:space-between;align-items:end;gap:30px;flex-wrap:wrap}.cta h2{margin:0 0 10px}.cta p{margin:0;max-width:600px}.button{display:inline-block;background:var(--ink);color:var(--paper);padding:18px 22px;text-decoration:none;font:700 12px/1 monospace;text-transform:uppercase;white-space:nowrap}footer{border-top:1px solid;border-bottom:0;margin-top:0}</style></head>
<body><div class="bar"><span>Revert Creations · free guide</span><span>No signup · no tracking · just the checklist</span></div><header><a class="brand" href="{{ route('home') }}">REVERT CREATIONS</a><a href="{{ route('storefront-audit', ['source' => 'holiday-guide-header']) }}">The full audit →</a></header><main>
<h1>The pre-holiday storefront check.</h1>
<p class="lead">Black Friday doesn't break stores. It sends thousands of people into whatever was already broken. Every check below takes minutes, needs no apps and no analytics — just your phone and a logged-out browser. Do this in August or September, while there's still time to fix what you find.</p>

<h2>Do this on your phone, logged out.</h2>
<p>Most of your holiday traffic will be a phone in someone's hand, not your desktop in Shopify admin. Open a private/incognito window so you see what a stranger sees.</p>

<div class="check"><h3>1 · Buy something, all the way to payment.</h3><p>Pick your bestseller. Tap through: product → options → add to cart → cart → begin checkout. Stop before paying.</p><p class="how">Watch for: option pickers that fail or hide error messages, the add-to-cart button not responding on first tap, the cart icon not updating, checkout buttons below the fold.</p></div>
<div class="check"><h3>2 · Try to break the variant picker.</h3><p>Select every combination of size/color/material on your most-optioned product. Then change your mind twice.</p><p class="how">Watch for: prices that don't update, sold-out combinations that still add to cart, selected options resetting when you scroll, error text appearing off-screen.</p></div>
<div class="check"><h3>3 · Abuse the cart.</h3><p>Add three items. Remove the middle one. Change a quantity to 10, then back to 1. Remove everything, then add something again.</p><p class="how">Watch for: totals that lag or go wrong, an emptied cart that still shows a price, remove buttons too small to tap, the page dumping you somewhere unexpected.</p></div>
<div class="check"><h3>4 · Rotate the phone. Resize the window.</h3><p>Do checks 1–3 in landscape. On desktop, drag the window narrow and wide.</p><p class="how">Watch for: overlapping text, buttons pushed off-screen, images covering controls, menus that won't close.</p></div>
<div class="check"><h3>5 · Follow your own navigation cold.</h3><p>Pretend you want a gift under $50. Start at the homepage. Find it using only menus and search — no URLs.</p><p class="how">Watch for: dead menu links, search that returns nothing for words customers actually use, collection pages with sold-out products first, no path back.</p></div>
<div class="check"><h3>6 · Open the browser console (desktop).</h3><p>Right-click → Inspect → Console tab. Reload the homepage, one product page, and the cart.</p><p class="how">Watch for: red errors that appear on every load. You don't need to understand them — screenshot them for whoever maintains your theme. Repeating red errors on the purchase path are never fine.</p></div>
<div class="check"><h3>7 · Test the announcement bar and popups.</h3><p>Holiday banners and discount popups get added in November — on top of whatever you have now. Trigger every popup, close every banner.</p><p class="how">Watch for: close buttons that miss on mobile, popups covering the add-to-cart button, banners pushing the buy box below the fold. Every new holiday element stacks onto this.</p></div>

<h2>What this check can't catch.</h2>
<p>This is a functional walkthrough at normal traffic. It won't tell you how your store behaves under load, whether your discount codes are configured correctly, or what happens to checkout at peak concurrency — those need different tools. And it only finds what happens to <em>you</em>: a systematic inspection covers viewport widths, console and network evidence, and the paths you don't think to try.</p>

<div class="cta"><div><h2>Want it done systematically?</h2><p>The Shopify Storefront Audit inspects five public pages at three viewport widths and delivers up to 12 prioritized findings with screenshots, exact URLs, and a repair order — in three business days, no store access needed. Booked in August or September, there's still time to fix everything it finds before the traffic arrives.</p></div><a class="button" href="{{ route('storefront-audit', ['source' => 'holiday-guide-cta']) }}">See the audit & sample report →</a></div>
</main><footer><span>© {{ date('Y') }} Revert Creations</span><span>support@revertcreations.com</span></footer></body></html>
