<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Fixed-price Shopify storefront auditing and packing-slip personalization services from Revert Creations."><link rel="canonical" href="{{ route('services') }}"><title>Shopify Services | Revert Creations</title>
<style>:root{--ink:#191914;--paper:#f1eee4;--signal:#ef5b35;--acid:#d8ed55;--blue:#3456a4}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Arial,sans-serif}a{color:inherit}.bar,header,footer{padding:14px clamp(20px,7vw,108px);border-bottom:1px solid;display:flex;justify-content:space-between;gap:20px;font:700 11px/1.4 monospace;letter-spacing:.1em;text-transform:uppercase}header{padding-top:24px;padding-bottom:24px}.brand{text-decoration:none}main{padding:0 clamp(20px,7vw,108px)}.hero{padding:78px 0 64px;display:grid;grid-template-columns:1.2fr .8fr;gap:8vw;align-items:end;border-bottom:1px solid}.eyebrow{font:700 11px/1.5 monospace;letter-spacing:.13em;text-transform:uppercase}h1,h2,h3{font-family:Georgia,serif;font-weight:500;letter-spacing:-.05em}h1{font-size:clamp(55px,7.5vw,105px);line-height:.88;margin:20px 0 28px}h2{font-size:clamp(38px,5vw,64px);line-height:.95;margin:0}h3{font-size:33px;line-height:1;margin:12px 0 18px}.lead{font:20px/1.5 Georgia,serif}.promise{background:var(--acid);padding:30px;box-shadow:12px 12px 0 var(--ink);font:14px/1.55 monospace}.section{padding:65px 0;border-bottom:1px solid}.section-head{display:grid;grid-template-columns:.7fr 1.3fr;gap:8vw;margin-bottom:45px}.cards{display:grid;grid-template-columns:1fr 1fr;gap:28px}.card{border:1px solid;padding:30px;background:#fffdf7;display:flex;flex-direction:column}.card:first-child{box-shadow:10px 10px 0 var(--signal)}.price{font:700 12px/1.5 monospace;letter-spacing:.1em;text-transform:uppercase}.card p{font:17px/1.55 Georgia,serif}.card li{font:14px/1.5 monospace;margin-bottom:10px}.button{display:inline-block;margin-top:auto;padding:18px 21px;background:var(--ink);color:var(--paper);text-decoration:none;font:700 12px monospace;text-transform:uppercase;align-self:flex-start}.fit{display:grid;grid-template-columns:1fr 1fr;gap:28px}.fit article{border-top:1px solid;padding-top:20px}.fit p{font:17px/1.58 Georgia,serif}.benchcue{background:var(--blue);color:white;padding:55px clamp(20px,7vw,108px);margin:0 calc(-1 * clamp(20px,7vw,108px));display:grid;grid-template-columns:.7fr 1.3fr;gap:8vw}.benchcue p{font:17px/1.58 Georgia,serif}footer{border-top:1px solid;border-bottom:0}@media(max-width:760px){.hero,.section-head,.cards,.fit,.benchcue{grid-template-columns:1fr}.bar span:last-child{display:none}.button{margin-top:20px}}</style></head>
<body><div class="bar"><span>Revert Creations · Shopify services</span><span>Fixed scope · fixed price · async</span></div><header><a class="brand" href="{{ route('home') }}">REVERT CREATIONS</a><a href="#services">Compare services →</a></header><main>
<section class="hero"><div><div class="eyebrow">Shopify help without an open-ended engagement</div><h1>Know exactly what you are buying.</h1><p class="lead">Two small services for two specific store problems. Each has a published price, a visible deliverable, and a stopping point.</p></div><aside class="promise"><strong>No sales call required.</strong><br><br>No retainer, admin login, customer data, theme access, or surprise implementation quote.</aside></section>
<section class="section" id="services"><div class="section-head"><div><div class="eyebrow">Choose by your problem</div><h2>Audit the store—or fix the packing slip.</h2></div><p class="lead">These are separate services. The audit does not include code changes. The packing-slip setup does one defined implementation and is not a general store review.</p></div><div class="cards">
<article class="card"><div class="price">$250 · delivered in 3 business days</div><h3>Shopify Storefront Audit</h3><p>For a live store with mobile friction, broken public behavior, confusing purchase paths, or visual problems that need a prioritized repair plan.</p><ul><li>5 public pages at desktop, tablet, and mobile widths</li><li>Up to 12 findings with URLs and annotated evidence</li><li>Severity, confidence, and recommended repair order</li><li>A complete demonstration report before you buy</li></ul><a class="button" href="{{ route('storefront-audit') }}">See scope and sample →</a></article>
<article class="card"><div class="price">$149 · delivered in 2 business days</div><h3>Shopify Packing-Slip Personalization</h3><p>For a store already collecting engraving, monogram, color, or other line-item properties that do not appear correctly on packing slips.</p><ul><li>A Liquid block matched to your actual field names</li><li>Installation instructions and validation</li><li>One consolidated revision</li><li>No theme or Shopify-admin access</li></ul><a class="button" href="{{ route('packing-slip-setup') }}">See the exact setup →</a></article>
</div></section>
<section class="section"><div class="section-head"><div><div class="eyebrow">Fit check</div><h2>Not every store should buy.</h2></div><p class="lead">A narrow service is useful only when its boundary matches the problem.</p></div><div class="fit"><article><h3>The audit fits if…</h3><p>You have a public Shopify store and need a reproducible outside view your developer, designer, or agency can act on. It is not analytics-based CRO and does not promise a conversion lift.</p></article><article><h3>The packing-slip setup fits if…</h3><p>Your product customization values already exist as public Shopify line-item properties. It does not create product options, change fulfillment, or install an app.</p></article></div></section>
<section class="benchcue"><div><div class="eyebrow">Software in Shopify review</div><h2>BenchCue</h2></div><div><p>A $7/month Shopify app for made-to-order stores. It shows public customization details on the order page and prints a focused production sheet without a maintained template.</p><p><a href="{{ route('benchcue.guide') }}"><strong>See the workflow and current availability →</strong></a></p></div></section>
</main><footer><span>© {{ date('Y') }} Revert Creations</span><span>support@revertcreations.com</span></footer></body></html>
