<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="A fixed-price Shopify packing-slip Liquid setup for real personalization field names, delivered asynchronously with installation notes and one revision."><link rel="canonical" href="{{ route('packing-slip-setup') }}"><title>Shopify Packing Slip Personalization Setup · $149 | Revert Creations</title><script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'Service','name'=>'Shopify Packing Slip Personalization Setup','provider'=>['@type'=>'Organization','name'=>'Revert Creations'],'serviceType'=>'Shopify packing-slip Liquid customization','areaServed'=>'Worldwide','offers'=>['@type'=>'Offer','price'=>'149','priceCurrency'=>'USD','url'=>route('packing-slip-setup')]], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) !!}</script>
<style>:root{--ink:#211d18;--paper:#f2eadb;--orange:#e85a32;--yellow:#f4d34c;--blue:#315ca8}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Arial,sans-serif}a{color:inherit}.bar,header,footer{padding:14px clamp(20px,7vw,108px);border-bottom:1px solid;display:flex;justify-content:space-between;gap:20px;font:700 11px/1.4 monospace;letter-spacing:.1em;text-transform:uppercase}header{padding-top:24px;padding-bottom:24px}.brand{text-decoration:none}main{padding:0 clamp(20px,7vw,108px)}.hero{padding:80px 0 65px;display:grid;grid-template-columns:1.2fr .8fr;gap:8vw;align-items:end;border-bottom:1px solid}.eyebrow{font:700 11px/1.5 monospace;letter-spacing:.13em;text-transform:uppercase}h1,h2,h3{font-family:Georgia,serif;font-weight:500;letter-spacing:-.05em}h1{font-size:clamp(55px,7.5vw,105px);line-height:.88;margin:20px 0 28px}h2{font-size:clamp(38px,5vw,64px);line-height:.95;margin:0}.lead{font:20px/1.5 Georgia,serif}.price{background:var(--orange);padding:30px;box-shadow:12px 12px 0 var(--ink)}.price strong{font:700 62px/.9 Georgia,serif}.price p{font:13px/1.5 monospace}.section{padding:65px 0;display:grid;grid-template-columns:.7fr 1.3fr;gap:8vw;border-bottom:1px solid}.copy p,.copy li{font:17px/1.58 Georgia,serif}.copy li{margin-bottom:12px}.scope{display:grid;grid-template-columns:1fr 1fr;gap:25px}.card{border-top:1px solid;padding:20px 0}.card h3{font-size:28px;margin:0 0 10px}.card p{margin:0}.example{margin:0;background:#fffdf7;border:1px solid;padding:24px;box-shadow:10px 10px 0 var(--orange);font:13px/1.65 monospace;white-space:pre-wrap;overflow-wrap:anywhere}.boundary{background:var(--ink);color:var(--paper);padding:52px clamp(20px,7vw,108px);margin:0 calc(-1 * clamp(20px,7vw,108px));display:grid;grid-template-columns:.7fr 1.3fr;gap:8vw}.boundary p,.boundary li{font:17px/1.58 Georgia,serif}.checkout{background:var(--yellow);padding:54px clamp(20px,7vw,108px);margin:0 calc(-1 * clamp(20px,7vw,108px));display:flex;justify-content:space-between;align-items:end;gap:35px}.checkout p{font:17px/1.5 Georgia,serif;max-width:680px}.button{display:inline-block;background:var(--ink);color:var(--paper);padding:19px 23px;text-decoration:none;font:700 12px/1 monospace;text-transform:uppercase;white-space:nowrap}footer{border-top:1px solid;border-bottom:0}@media(max-width:760px){.hero,.section,.boundary{grid-template-columns:1fr}.scope{grid-template-columns:1fr}.checkout{align-items:flex-start;flex-direction:column}.bar span:last-child{display:none}}</style></head>
<body><div class="bar"><span>Revert Creations · fixed-scope Shopify service</span><span>No call · no credentials · async delivery</span></div><header><a class="brand" href="{{ route('home') }}">REVERT CREATIONS</a><a href="{{ route('benchcue.packing-slip-guide') }}">Read the free guide →</a></header><main>
<section class="hero"><div><div class="eyebrow">For personalized and made-to-order Shopify products</div><h1>Personalization details, printed on every packing slip.</h1><p class="lead">Engraving text, monograms, gift notes—if your orders collect them, your packing slips can print them. Tell us your field names and receive ready-to-paste template code, installation notes, and one written revision—without sharing a store login.</p></div><aside class="price"><strong>$149</strong><p>One-time · delivered asynchronously within two business days after usable intake · one revision included</p></aside></section>
<section class="section"><div><div class="eyebrow">Exactly what arrives</div><h2>A small, usable implementation package.</h2></div><div class="copy scope"><article class="card"><h3>Ready-to-paste template code</h3><p>A code block (Shopify "Liquid") matched to the exact field names you provide, with blank values and other apps' internal fields handled deliberately.</p></article><article class="card"><h3>Installation notes</h3><p>Where the block belongs in Shopify's packing-slip template, what to preview, and how to revert safely.</p></article><article class="card"><h3>Checked before delivery</h3><p>The code is validated before it's sent. Store-specific data availability still requires previewing a real order.</p></article><article class="card"><h3>One revision</h3><p>One consolidated written revision submitted within seven days of delivery.</p></article></div></section>
<section class="section"><div><div class="eyebrow">Illustrative excerpt</div><h2>See the kind of code delivered.</h2></div><div class="copy"><p>This example uses fictional fields. A paid delivery is narrowed to the public field names supplied at checkout and includes placement and preview instructions.</p><pre class="example"><code>@verbatim{% for property in line_item.properties %}
  {% assign first_character = property.first | slice: 0 %}
  {% if property.last != blank and first_character != '_' %}
    &lt;div&gt;&lt;strong&gt;{{ property.first }}:&lt;/strong&gt;
      {{ property.last }}&lt;/div&gt;
  {% endif %}
{% endfor %}@endverbatim</code></pre></div></section>
<section class="boundary"><div><div class="eyebrow">Firm boundary</div><h2>No store login. No hidden project.</h2></div><div><p>This is a code-and-instructions delivery, not access to your Shopify admin.</p><ul><li>No credentials, collaborator access, theme changes, or installation.</li><li>One packing-slip block for one store and one described field set.</li><li>No app customization, order export, production queue, shipping workflow, or customer-data migration.</li><li>No guarantee of revenue, conversion, or compatibility with undocumented third-party data.</li><li>If the supplied field names are unusable, delivery pauses until usable written intake arrives.</li></ul></div></section>
<section class="section"><div><div class="eyebrow">After payment</div><h2>Everything stays asynchronous.</h2></div><div class="copy"><ol><li>Enter your Shopify store URL and the personalization field names at checkout.</li><li>We prepare and validate your template code.</li><li>Delivery goes to the checkout email within two business days after usable intake.</li><li>Reply with one consolidated revision request if needed.</li></ol><p>Do not submit customer names, order contents, passwords, private theme code, or API credentials.</p><p>If the problem is broader than a packing slip, the <a href="{{ route('storefront-audit', ['source' => 'packing-slip-offer']) }}">Shopify Storefront Audit</a> inspects public functionality, responsive behavior, experience friction, and performance signals without store access.</p></div></section>
<section class="checkout" id="checkout"><div><div class="eyebrow">Fixed price · bounded scope</div><h2>Buy the packing-slip setup.</h2><p>Stripe checkout collects your email, public store URL, and the names of the public personalization fields you want printed.</p></div><a class="button" href="{{ route('packing-slip-setup.checkout', ['source' => $acquisitionSource]) }}">Buy for $149 →</a></section>
</main><footer><span>© {{ date('Y') }} Revert Creations</span><span>support@revertcreations.com</span></footer></body></html>
