module.exports = {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
    ],
    darkMode: 'media',
    theme: {
        extend: {
            fontFamily: {
                sans: ['"Inter var"', 'Inter', 'system-ui', 'sans-serif'],
                display: ['"Playfair Display"', 'serif'],
            },
            colors: {
                'revert-black': '#2a2727',
                'revert-gray': '#c1bfbe',
                'revert-yellow': '#f0d43a',
                'revert-green': '#c1e718',
                'revert-blue': '#22b2da',
                'gruvbox-light-red': '#fb3934',
                'gruvbox-red': '#cc241d',
                'gruvbox-light-yellow': '#d79921',
                'gruvbox-yellow': '#fabd2f',
                'gruvbox-light-orange': '#d65d0e',
                'gruvbox-orange': '#fe8019',
                'gruvbox-light-blue': '#458588',
                'gruvbox-blue': '#83a598',
                'gruvbox-light-aqua': '#689d6a',
                'gruvbox-aqua': '#8ec07c',
                'gruvbox-gray': '#a89984',
                'gruvbox-light-green': '#98971a',
                'gruvbox-green': '#b8bb26',
                'gruvbox-light-purple': '#d3869b',
                'gruvbox-purple': '#b16286',
                'gruvbox-black': '#282828',
                'gruvbox-black-hidden': '#32302f',
                'gruvbox-white': '#fbf1c7',
                'hmt-green': '#b9cc33',
                'motorsportreg-red': '#f13a44',
                'gruvbox-charcoal': '#1f1f1f',
                'gruvbox-stone': '#2b2b2b',
                'gruvbox-highlight': '#3c3836',
            },
            boxShadow: {
                card: '0 16px 32px -20px rgba(0,0,0,0.45)',
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
    ],
};
